export default function () {
  return (
    <>
    <h1>August 29, 2024 11:50 AM</h1>
    <p>Sigh, took me far longer than I would like to get a new page started. I could probably create some kind of bash script that does everything and opens an editor. But despite being able to think that thought...I'm not actually going to do it.</p>
    <p>Did a Working Genius assessment this week and I'm 50/50 on it being a hoax and learning a bunch from it. I think it's more of a marketing hoax in terms of how hyped up it is, but I think there's still value in understanding and reflecting on the model.  I apparently have Wonder and Discernment as my top 2. I can see how Galvanizing and Enablement are definitely not it.  But I think I was surprised Invention wasn't a top one and especially surprised to see Tenacity as one of my lower ones.</p>
    <p>On reflection, it all started to make more sense though. I actually hate completing tasks. I love to wonder about how something might work and then I quickly lob it over to my Discernment side of things and then once I've learned what I wanted to I'm good.  Recently I've found the only way to properly complete tasks is to have someone watching me the entire time I'm doing it. The peer pressure forces me to push through the discomfort of completing a task. I have already started doing this with pair coding and livestreaming.</p>
    <p>Even writing this post is a struggle for me. This morning I worked out and then did a pair coding session from 9-11. I feel like I've basically emptied my cup by staying in Tenacity for too long.  Having an Enablement person with me helped quite a bit, but even then there's still a limit.</p>
    <p>So now I wonder what I should do with my time. I don't have the energy to do things that don't fill the cup.  So logically sounds like I need to fill my cup.  If this assessment is accurate, that means I need to wonder something (which maybe writing this post is that?) and discern something (also kind of feels like what this post is).  Just based on what I've written so far, it sounds like I enjoy the wondering part of this, struggle with the "invention" part of actually writing it down, and then enjoy the discernment once I actually have. I wonder if this is where a therapist comes into play. If I was struggling to make it through one of the steps, they would help boost me through it.</p>
    <p>A little bit challenging writing this in what is supposed to be a public forum and my brain decides to interrupt with more personal things that I don't actually want to be public. And again my brain goes: "I wonder if there's a way to solve that with software".</p>
    <p>I feel this immense guilt for feeling incapable of "working" in a get shit done kind of manner.  But, in reality I think there's quite a bit of wondering and discernment that needs to occur to make sure things are on the right path.  Maybe what I'm feeling is altitude sickness from just being on the ground pumping out code changes to trying to jump all the way to the big picture.</p>
    <p>I'm almost shocked at how much better I've felt essentially microdosing caffeine. When I used to have a regular coffee in the morning I would peak in anxiety and practically shit myself (literally). Now I do I very weak decaf anytime before 12PM and I find myself not feeling tired for the entire day.  I've also been taking iron and magnesium consistently and have historically found that helps my energy levels. There very well could be a fair bit of placebo effect with the coffee in me believing that it keeps me awake (and I'm all for that).</p>
    <p>My restlessness is definitely growing. Makes me wonder if I need to taper off caffeine by the end of the week so I can return to normal.  Nowadays when 10PM rolls around, I don't even feel tired. Which makes it hard to go to bed and when I do I have more RLS than usual.</p>
    <p>"What should I be doing right now?" is a common question I find myself landing on. Which considering how much I know needs to be done is not ideal. This probably indicates that tasks aren't broken down enough or aren't prioritized well enough. I can think of all the things I should be doing, but I get stuck pondering which one I should be focused on first. </p>
    <p>Just had a bit of a "brain blast" that I would classify on the Wonder side of things. I don't even really know what it was. Something about using JavaScript as the language for tutorials (like showing how to set up IG API), but then in reality I would prefer to use something like Rust. Which is usually quickly followed by the fact that I find the learning process of rust quite painful. Which maybe the full cycle of the thought is that Rust education is a problem. When I have good documentation for Rust, I don't really have any problems understanding it.  But every small new thing you try to do takes a lot of effort and I usually just go, well I could do this in 2 seconds in JS and give up.  But I feel pretty strongly that JS should not be the language of the future.  Especially not if we have computers writing our code. Which is a whole nother rabbit hole of "if computers write code, do we need to have a 'safe' programming language?"</p>
    <p>All of this feels esoteric and useless. But I do feel my cup refilling, so does it matter? I don't really expect anyone to read this, so I'm wasting no ones time but my own. What I really want out of writing some of this is to stop thinking the same thought over and over. It often feels like I'm in a maze, but having the same thought over and over again is like being stuck in the same section of a maze. There's really only two options in my mind "do it" or "let it go". This happens to me a lot, so let it go is usually the default.  But I feel like when something resurfaces multiple times, the only way to let it go is to do it.  Plus I usually get a hit of dopamine whenever I cross one of these things off my list.  And I get excited about what new door reveals itself after.</p>
    <p>I'm at 12:30 PM now and had to lie down in order to make it through writing this. Often quite long pauses between writing things that are kind of like micronaps. I once read that Ben Franklin (I think) would sit in a chair holding something and wait til he dozed off and then would drop the thing he was holding and wake up so he could write down whatever thought he was having in that moment. I think this serves that same purpose for me. The difference is that my brain works in a more digital manner. So I end up having to type quite a bit to consolidate what I'm actually thinking. Or maybe that was the same case for him back in the day and it just took significantly longer because he was limited by how quickly he could write things down. But I imagine being forced to work with just a pen and paper would strengthen ones ability to reduce how much needed to be written down.</p>
    <p>Took like 2 minutes to "nap" and started some thought about being a shapeshifter/chameleon. I think what's confusing about this working genius assessment is that in past roles, I think I have taken on and enjoyed totally different things. Or maybe I didn't realize or masked the fact that I wasn't actually enjoying them. Like I used to be one of the people primarily responsible for getting shit done inside the codebase. But maybe as I reflect back on that, I was doing out of neccesity and maybe that explains why it ended up burning me out so quickly. A later time I was in a position of much more enablement. I feel like I knew how to do it well and generally did, but didn't really enjoy doing it. My initial burst could have been from just wondering what different approaches could be like, but once I wore through that I was left saddled with execution.</p>
    <p>Based on observations, it seems like I've got about 3-4 hours that I can muster through more execution oriented tasks. What I think I need to do is find how I can fill my cup for the rest of the day while still providing forward momentum for kaizen.place. </p>
    <p>The best idea I have so far is to use some of that Wonder/Discernment energy to create some kind of content. I think my hang up is that this naturally creates more work for myself later and I can't follow through.  An alternative with maybe less overhead is some kind of regularly scheduled livestream where I have somethingl loosely planned for, but if people actually showed up we could derail quite a bit a kind of just "hang out". This would ensure I'm consistently using our livestreaming functionality and understanding what it needs and thinking like a creator to understand what we should be building.</p>
    <p>I think what stops me from doing this is that to do it effectively, I need to pre-plan and market ahead of time. I think I would be much better off having a fixed schedule that I stick to and that way even if I don't market, eventually prospective viewers can learn the schedule and tune in when works for them.</p>
    <p>ok, I think that's enough running in circles for now.  It's been a full hour. I think I'll try to take a proper nap to reset and then switch mediums to pencil and paper and come up with a plan for my afternoon.</p>
    </>
  );
}
